#!/usr/bin/env python3
#
# diagnostics-vocabulary.py — regenerate Sources/CryoframeKit/DiagnosticsVocabulary.swift,
# the words the problem report may keep from free text (see Redactor in Diagnostics.swift).
#
# The words are those of the string literals in the files below: what Cryoframe itself
# writes into the run history and the check records. Run it after adding or changing
# a message; DiagnosticsTests fails with the missing words until then.
#   ./scripts/diagnostics-vocabulary.py
#
import glob, os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
OUT = os.path.join(ROOT, "Sources/CryoframeKit/DiagnosticsVocabulary.swift")

def sources():
    files = sorted(glob.glob(os.path.join(ROOT, "Sources/CryoframeKit/*.swift")))
    files += sorted(glob.glob(os.path.join(ROOT, "Sources/CryoframeShared/*.swift")))
    files += [os.path.join(ROOT, "Sources/Cryoframe", f) for f in ("AgentMain.swift", "HealthSchedule.swift", "RehearsalSchedule.swift")]
    return [f for f in files if not f.endswith("DiagnosticsVocabulary.swift")]

def words(text):
    text = re.sub(r"//[^\n]*", "", text)
    out = set()
    for m in re.finditer(r'"((?:[^"\\\n]|\\.)*)"', text):
        literal = re.sub(r"\\\((?:[^()]|\([^()]*\))*\)", " ", m.group(1))
        for w in re.findall(r"[A-Za-z][A-Za-z'’]*", literal):
            w = w.lower().replace("’", "'")
            # no single letters but "a" (Redactor.isVocabularyWord): they come from
            # "%d" and "\n", and let a name split around an accent keep its pieces
            if len(w) > 1 or w == "a":
                out.add(w)
    return out

def main():
    vocab = set()
    for f in sources():
        with open(f, encoding="utf-8") as fh:
            vocab |= words(fh.read())
    body = "\n".join(sorted(vocab))       # one word a line, so a change shows as itself
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(f'''//
//  DiagnosticsVocabulary.swift
//  CryoframeKit
//
//  Generated by scripts/diagnostics-vocabulary.py from the string literals of the
//  messages Cryoframe writes into its history. Don't edit by hand: change a message,
//  then run the script. See Redactor in Diagnostics.swift.
//

extension Redactor {{
    static let productWords: Set<String> = Set("""
{body}
""".split(whereSeparator: {{ $0 == " " || $0 == "\\n" }}).map(String.init))
}}
''')
    print(f"{len(vocab)} words -> {os.path.relpath(OUT, ROOT)}")

if __name__ == "__main__":
    main()
